# Generated by Django 5.2.11 on 2026-02-10 21:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du conteneur')),
                ('objectif', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Objectif')),
                ('devise', models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar américain'), ('CNY', 'Yuan chinois')], default='GNF', max_length=3, verbose_name='Devise')),
                ('montant_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant actuel (GNF)')),
                ('etape', models.CharField(choices=[('collecte', 'Collecte'), ('mer', 'En Mer'), ('port', 'Au Port')], default='collecte', max_length=20, verbose_name='Étape')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('annule', models.BooleanField(default=False, verbose_name='Annulé')),
            ],
            options={
                'verbose_name': 'Conteneur',
                'verbose_name_plural': 'Conteneurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TauxDeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(choices=[('USD', 'Dollar américain'), ('CNY', 'Yuan chinois'), ('EUR', 'Euro')], max_length=3, verbose_name='Devise')),
                ('taux_gnf', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taux vers GNF')),
                ('date_application', models.DateTimeField(auto_now_add=True, verbose_name="Date d'application")),
                ('actif', models.BooleanField(default=True, verbose_name='Taux actif')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['-date_application'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(max_length=15, unique=True, verbose_name='Numéro de téléphone')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Code OTP')),
                ('otp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Date création OTP')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='Téléphone vérifié')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (GNF)')),
                ('reference_paiement', models.CharField(max_length=100, verbose_name='Référence Orange Money')),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to='preuves_paiement/', verbose_name='Preuve de paiement')),
                ('valide', models.BooleanField(default=False, verbose_name='Paiement validé')),
                ('date_participation', models.DateTimeField(auto_now_add=True, verbose_name='Date de participation')),
                ('conteneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conteneur', verbose_name='Conteneur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'ordering': ['-date_participation'],
            },
        ),
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde (GNF)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('depot', 'Dépôt'), ('retrait', 'Retrait'), ('participation', 'Participation conteneur'), ('remboursement', 'Remboursement')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (GNF)')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('conteneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conteneur', verbose_name='Conteneur')),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.portefeuille', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
