# Generated by Django 5.2.11 on 2026-02-10 23:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='preuve_paiement',
            field=models.ImageField(blank=True, help_text='Formats acceptés: JPG, PNG (max 5MB)', null=True, upload_to='preuves_paiement/%Y/%m/', validators=[core.validators.validate_file_extension, core.validators.validate_file_size, core.validators.validate_image], verbose_name='Preuve de paiement'),
        ),
    ]
