# Generated by Django 5.2.11 on 2026-02-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_participation_preuve_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fournisseur')),
                ('categorie', models.CharField(choices=[('TEXTILE', 'Mode & Textile'), ('ELECTRO', 'Électronique & Accessoires'), ('BEAUTE', 'Beauté & Cosmétiques'), ('MAISON', 'Maison & Quincaillerie')], max_length=20, verbose_name='Catégorie')),
                ('badges_confiance', models.CharField(max_length=200, verbose_name='Badges de confiance')),
                ('specialite', models.TextField(verbose_name='Spécialité de produits')),
                ('moq', models.CharField(max_length=100, verbose_name='MOQ (Commande minimum)')),
                ('argument_vente', models.TextField(verbose_name='Argument de vente pour Madina')),
                ('annees_experience', models.IntegerField(default=0, verbose_name="Années d'expérience")),
                ('pays_origine', models.CharField(choices=[('CHINE', 'Chine'), ('DUBAI', 'Dubaï'), ('TURQUIE', 'Turquie')], default='CHINE', max_length=20, verbose_name="Pays d'origine")),
                ('verifie', models.BooleanField(default=True, verbose_name='Fournisseur vérifié')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
