# Generated by Django 5.2.11 on 2026-02-11 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteneur',
            name='capacite_max_cbm',
            field=models.DecimalField(decimal_places=3, default=76, help_text='76 CBM pour un conteneur 40HC', max_digits=8, verbose_name='Capacité max (CBM)'),
        ),
        migrations.AddField(
            model_name='conteneur',
            name='volume_total_cbm',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Volume total (CBM)'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_produit', models.TextField(verbose_name='Description du produit')),
                ('categorie_produit', models.CharField(choices=[('ELECTRONIQUE', 'Électronique'), ('TEXTILE', 'Textile & Vêtements'), ('DIVERS', 'Divers')], default='DIVERS', max_length=20)),
                ('prix_achat_yuan', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'achat (Yuan)")),
                ('volume_cbm', models.DecimalField(decimal_places=3, help_text='Mètres cubes', max_digits=8, verbose_name='Volume (CBM)')),
                ('taux_change', models.DecimalField(decimal_places=2, default=1250, max_digits=10, verbose_name='Taux Yuan → GNF')),
                ('commission_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Commission (%)')),
                ('prix_achat_gnf', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix achat (GNF)')),
                ('frais_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Commission plateforme')),
                ('frais_logistique', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Frais logistique')),
                ('total_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total à payer (GNF)')),
                ('montant_fournisseur', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Part fournisseur')),
                ('montant_transitaire', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Part transitaire')),
                ('marge_plateforme', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Marge plateforme')),
                ('statut', models.CharField(choices=[('devis', 'Devis en cours'), ('confirme', 'Confirmé'), ('paye', 'Payé'), ('expedie', 'Expédié'), ('recu', 'Reçu')], default='devis', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('conteneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='core.conteneur')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fournisseur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
